# Generated by Django 4.1.3 on 2023-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeliculasDeCulto', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculasdeculto',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
