# Generated by Django 4.1.3 on 2023-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeliculasDeCulto', '0004_remove_peliculasdeculto_id_peliculasdeculto_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculasdeculto',
            name='category',
        ),
        migrations.AddField(
            model_name='peliculasdeculto',
            name='categories',
            field=models.ManyToManyField(to='PeliculasDeCulto.category'),
        ),
    ]
