# Generated by Django 4.1.3 on 2023-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeliculasDeCulto', '0005_remove_peliculasdeculto_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculasdeculto',
            name='isHome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peliculasdeculto',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
